import { Segment } from '@prisma/client';
import axios from 'axios';
import prisma from './prisma';

interface PlaylistOptions {
  name: string;
  description?: string;
  timeRangeStart: Date;
  timeRangeEnd: Date;
  segments?: Segment[];
  friendIds?: string[];
}

export async function generatePlaylist(userId: string, opts: PlaylistOptions) {
  const userIds = opts.friendIds?.length ? [...opts.friendIds, userId] : [userId];

  const where: any = {
    userId: { in: userIds },
    segmentDate: { gte: opts.timeRangeStart, lte: opts.timeRangeEnd },
    status: { in: ['CONFIRMED', 'LATE'] },
    isSilent: false,
  };
  if (opts.segments?.length) {
    where.segment = { in: opts.segments };
  }

  const replays = await prisma.replay.findMany({
    where,
    orderBy: { captureTime: 'asc' },
  });

  // Deduplicate by trackUri
  const unique = new Map<string, any>();
  for (const r of replays) {
    if (r.trackUri && !unique.has(r.trackUri)) {
      unique.set(r.trackUri, {
        trackUri: r.trackUri,
        trackName: r.trackName,
        artistName: r.artistName,
        albumArtUrl: r.albumArtUrl,
      });
    }
  }
  const tracks = [...unique.values()];

  const playlist = await prisma.playlist.create({
    data: {
      userId,
      name: opts.name,
      description: opts.description,
      timeRangeStart: opts.timeRangeStart,
      timeRangeEnd: opts.timeRangeEnd,
      segmentsIncluded: opts.segments || [],
      friendIdsIncluded: opts.friendIds || [],
      trackCount: tracks.length,
    },
  });

  return { id: playlist.id, name: playlist.name, trackCount: tracks.length, tracks };
}

export async function exportToSpotify(playlistId: string) {
  const playlist = await prisma.playlist.findUniqueOrThrow({
    where: { id: playlistId },
    include: { user: true },
  });

  const userIds = playlist.friendIdsIncluded.length
    ? [...playlist.friendIdsIncluded, playlist.userId]
    : [playlist.userId];

  const replays = await prisma.replay.findMany({
    where: {
      userId: { in: userIds },
      segmentDate: { gte: playlist.timeRangeStart!, lte: playlist.timeRangeEnd! },
      status: { in: ['CONFIRMED', 'LATE'] },
      isSilent: false,
      trackUri: { not: null },
    },
  });

  const uris = [...new Set(replays.map(r => r.trackUri!))];

  // Create Spotify playlist
  const { data: created } = await axios.post(
    `https://api.spotify.com/v1/users/${playlist.user.musicServiceUserId}/playlists`,
    { name: playlist.name, description: playlist.description || 'Generated by Replay', public: false },
    { headers: { Authorization: `Bearer ${playlist.user.accessToken}` } },
  );

  // Add tracks in batches of 100
  for (let i = 0; i < uris.length; i += 100) {
    await axios.post(
      `https://api.spotify.com/v1/playlists/${created.id}/tracks`,
      { uris: uris.slice(i, i + 100) },
      { headers: { Authorization: `Bearer ${playlist.user.accessToken}` } },
    );
  }

  await prisma.playlist.update({
    where: { id: playlistId },
    data: {
      exportedTo: 'SPOTIFY',
      externalPlaylistId: created.id,
      externalPlaylistUrl: created.external_urls.spotify,
    },
  });

  return {
    externalPlaylistId: created.id,
    externalPlaylistUrl: created.external_urls.spotify,
    trackCount: uris.length,
  };
}
